### ISSUE TITLE
DB2 Driver 

### ISSUE THREAD

**Issue by bradyburke** [IBM/presto-db2#47]
Trying to load the connector into a local copy of the open-source prestoSql/presto repo. It can not find the db2Driver in client module. Does the jar file need to be placed in the module? I thought since it's in there as a Maven dependency it should be downloaded upon building. What is the issue here?

**Comment by shawnzhu** [comment]
> Does the jar file need to be placed in the module?

Nope. it will fetch the db2 JDBC type 4 driver from maven repository during `mvn install`. see https://github.com/IBM/presto-db2/blob/acc92bfe7f408255c61d448503c316069b4085e9/pom.xml#L17-L21

It should work if you want to build this connector with `prestosql/presto` from source instead of released packages, however, you will need to tweak the `pom.xml` of `prestosql/presto` to include this connector as a module.
